name: Deploy to EKS with Helm

on:
  push:
    branches: [ main ]
    paths:
      - hello-world/**
     

env:
  AWS_REGION: eu-nooth-1


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          cd app
          docker build -t ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }} .
          docker push ${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.27.0

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name  ${{ secrets.EKS_CLUSTER_NAME }} --region $AWS_REGION

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.1

      - name: Deploy with Helm
        run: |
          helm upgrade --install hello-world ./hello-world/helm \
            --namespace default \
            --create-namespace
            --set image.tag=${{ secrets.ECR_REPOSITORY }:${{ github.sha }}
